//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanwhaClient.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HanwhaClient.Application.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format. Only .aes files are supported..
        /// </summary>
        internal static string AESFileFormat {
            get {
                return ResourceManager.GetString("AESFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All devices uploaded successfully..
        /// </summary>
        internal static string AllDeviceUploaded {
            get {
                return ResourceManager.GetString("AllDeviceUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and vehicle occupancy rate.
        /// </summary>
        internal static string AndVehicleOccupancyRate {
            get {
                return ResourceManager.GetString("AndVehicleOccupancyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} is on gate {3}.
        /// </summary>
        internal static string ANPRVehicleNotFound {
            get {
                return ResourceManager.GetString("ANPRVehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application cache cleared..
        /// </summary>
        internal static string ApplicationCacheClear {
            get {
                return ResourceManager.GetString("ApplicationCacheClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are busier than.
        /// </summary>
        internal static string AreBusierThan {
            get {
                return ResourceManager.GetString("AreBusierThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average People Occupancy Rate.
        /// </summary>
        internal static string AveragePeopleOccupancyRate {
            get {
                return ResourceManager.GetString("AveragePeopleOccupancyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Vehicle Occupancy Rate.
        /// </summary>
        internal static string AverageVehicleOccupancyRate {
            get {
                return ResourceManager.GetString("AverageVehicleOccupancyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Site.
        /// </summary>
        internal static string BySite {
            get {
                return ResourceManager.GetString("BySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Zone.
        /// </summary>
        internal static string ByZone {
            get {
                return ResourceManager.GetString("ByZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate expires soon: {0}.
        /// </summary>
        internal static string CertificateExpiresSoon {
            get {
                return ResourceManager.GetString("CertificateExpiresSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate has expired on {0}.
        /// </summary>
        internal static string CertificateHasExpired {
            get {
                return ResourceManager.GetString("CertificateHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate chain validation failed - certificate may not be trusted.
        /// </summary>
        internal static string CertificateNotTrusted {
            get {
                return ResourceManager.GetString("CertificateNotTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is not valid until {0}.
        /// </summary>
        internal static string CertificateNotValid {
            get {
                return ResourceManager.GetString("CertificateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Site not found.
        /// </summary>
        internal static string ChildSiteNotFound {
            get {
                return ResourceManager.GetString("ChildSiteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child site does not exist under the selected parent site..
        /// </summary>
        internal static string ChildSiteUnAvailable {
            get {
                return ResourceManager.GetString("ChildSiteUnAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        internal static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials. Please check your username and password..
        /// </summary>
        internal static string CredetialWrongAddDevice {
            get {
                return ResourceManager.GetString("CredetialWrongAddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file generated successfully..
        /// </summary>
        internal static string CsvGenerated {
            get {
                return ResourceManager.GetString("CsvGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dashboard with this name already exists..
        /// </summary>
        internal static string DashboardNameAlreadyExist {
            get {
                return ResourceManager.GetString("DashboardNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard name is required..
        /// </summary>
        internal static string DashboardNameMandatory {
            get {
                return ResourceManager.GetString("DashboardNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Restore failed.
        /// </summary>
        internal static string DatabaseRestoreFailed {
            get {
                return ResourceManager.GetString("DatabaseRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        internal static string DateTimeLabel {
            get {
                return ResourceManager.GetString("DateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A device with the same IP address already exists..
        /// </summary>
        internal static string DeviceAlreadyExists {
            get {
                return ResourceManager.GetString("DeviceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device limit has been reached. Please contact your administrator to upgrade the license..
        /// </summary>
        internal static string DeviceLimitExceededLicense {
            get {
                return ResourceManager.GetString("DeviceLimitExceededLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} is not allowed on gate {3}.
        /// </summary>
        internal static string DeviceNotAllowed {
            get {
                return ResourceManager.GetString("DeviceNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not registered.
        /// </summary>
        internal static string DeviceNotRegistered {
            get {
                return ResourceManager.GetString("DeviceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not registered for IP {0}.
        /// </summary>
        internal static string DeviceNotRegisteredForIP {
            get {
                return ResourceManager.GetString("DeviceNotRegisteredForIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is currently unavailable or offline. Please verify the connection and try again..
        /// </summary>
        internal static string DeviceUnavailable {
            get {
                return ResourceManager.GetString("DeviceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor name already exists. Please choose a different name..
        /// </summary>
        internal static string DuplicateFloor {
            get {
                return ResourceManager.GetString("DuplicateFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone name already exists on this floor. Please choose a different name..
        /// </summary>
        internal static string DuplicateZoneName {
            get {
                return ResourceManager.GetString("DuplicateZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided email address is not registered..
        /// </summary>
        internal static string EmailNotRegistered {
            get {
                return ResourceManager.GetString("EmailNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully..
        /// </summary>
        internal static string EmailSentSuccessfully {
            get {
                return ResourceManager.GetString("EmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating PFX file: {0}.
        /// </summary>
        internal static string ErrorValidatingPFXFile {
            get {
                return ResourceManager.GetString("ErrorValidatingPFXFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm event already exists..
        /// </summary>
        internal static string EventAlreadyExist {
            get {
                return ResourceManager.GetString("EventAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file does not contain any sheet..
        /// </summary>
        internal static string ExcelFileNotSheet {
            get {
                return ResourceManager.GetString("ExcelFileNotSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file generated successfully..
        /// </summary>
        internal static string ExcelGenerated {
            get {
                return ResourceManager.GetString("ExcelGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file is missing required columns: {0}.
        /// </summary>
        internal static string ExcelMissingColumn {
            get {
                return ResourceManager.GetString("ExcelMissingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete owner or associated vehicles..
        /// </summary>
        internal static string FailedToDeleteOwnerOrVehicle {
            get {
                return ResourceManager.GetString("FailedToDeleteOwnerOrVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to close the gate..
        /// </summary>
        internal static string FailToCloseGate {
            get {
                return ResourceManager.GetString("FailToCloseGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to open gate barrier for {0}..
        /// </summary>
        internal static string FailToOpenGateBarrierDesc {
            get {
                return ResourceManager.GetString("FailToOpenGateBarrierDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to Open Gate Barrier.
        /// </summary>
        internal static string FailToOpenGateBarrierTitle {
            get {
                return ResourceManager.GetString("FailToOpenGateBarrierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the gate..
        /// </summary>
        internal static string FailToOpenGateManually {
            get {
                return ResourceManager.GetString("FailToOpenGateManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format. Please upload a valid Excel file (.xlsx or .xls)..
        /// </summary>
        internal static string FileFormatInvalid {
            get {
                return ResourceManager.GetString("FileFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been successfully uploaded..
        /// </summary>
        internal static string FileUploaded {
            get {
                return ResourceManager.GetString("FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was uploaded..
        /// </summary>
        internal static string FileUploadFailure {
            get {
                return ResourceManager.GetString("FileUploadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Applied.
        /// </summary>
        internal static string FilterApplied {
            get {
                return ResourceManager.GetString("FilterApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        internal static string Floors {
            get {
                return ResourceManager.GetString("Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP configuration saved successfully..
        /// </summary>
        internal static string FtpConfugurationSave {
            get {
                return ResourceManager.GetString("FtpConfugurationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate Access Denied.
        /// </summary>
        internal static string GateAccessDenied {
            get {
                return ResourceManager.GetString("GateAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate opened successfully..
        /// </summary>
        internal static string GateOpenSuccessManually {
            get {
                return ResourceManager.GetString("GateOpenSuccessManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google API key saved successfully..
        /// </summary>
        internal static string GoogleApisave {
            get {
                return ResourceManager.GetString("GoogleApisave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has the highest people and vehicle occupancy rates.
        /// </summary>
        internal static string HasHighestPeopleAndVehicleOccupancyRates {
            get {
                return ResourceManager.GetString("HasHighestPeopleAndVehicleOccupancyRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has the highest number of people counted.
        /// </summary>
        internal static string HasHighestPeopleCount {
            get {
                return ResourceManager.GetString("HasHighestPeopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has the highest people occupancy rate.
        /// </summary>
        internal static string HasHighestPeopleOccupancyRate {
            get {
                return ResourceManager.GetString("HasHighestPeopleOccupancyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has the highest number of vehicles counted.
        /// </summary>
        internal static string HasHighestVehicleCount {
            get {
                return ResourceManager.GetString("HasHighestVehicleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has the highest vehicle occupancy rate.
        /// </summary>
        internal static string HasHighestVehicleOccupancyRate {
            get {
                return ResourceManager.GetString("HasHighestVehicleOccupancyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header row not found in Excel file..
        /// </summary>
        internal static string HeaderRowNotExits {
            get {
                return ResourceManager.GetString("HeaderRowNotExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS site {0} not found.
        /// </summary>
        internal static string IISSiteNotFound {
            get {
                return ResourceManager.GetString("IISSiteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the necessary permissions to perform this action..
        /// </summary>
        internal static string InsufficientPermissions {
            get {
                return ResourceManager.GetString("InsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient permissions to configure IIS. Please run with administrator privileges or configure application pool identity..
        /// </summary>
        internal static string InsufficientPermissionsForIIS {
            get {
                return ResourceManager.GetString("InsufficientPermissionsForIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided data model is invalid..
        /// </summary>
        internal static string InvalidDataModel {
            get {
                return ResourceManager.GetString("InvalidDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided Google API key is invalid. Please verify the key and try again..
        /// </summary>
        internal static string InvalidGoogleKey {
            get {
                return ResourceManager.GetString("InvalidGoogleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license is invalid. Please upload a valid license file..
        /// </summary>
        internal static string InvalidLicense {
            get {
                return ResourceManager.GetString("InvalidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PFX file or incorrect password.
        /// </summary>
        internal static string InvalidPFXFileIncorrectPassword {
            get {
                return ResourceManager.GetString("InvalidPFXFileIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Performance Metric.
        /// </summary>
        internal static string KeyPerformanceMetric {
            get {
                return ResourceManager.GetString("KeyPerformanceMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License has been authenticated successfully..
        /// </summary>
        internal static string LicenseAuthenticated {
            get {
                return ResourceManager.GetString("LicenseAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license has expired..
        /// </summary>
        internal static string LicenseExpired {
            get {
                return ResourceManager.GetString("LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License file not found..
        /// </summary>
        internal static string LicenseFileNotFound {
            get {
                return ResourceManager.GetString("LicenseFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file types. License file must be .lic and public key file must be .pem..
        /// </summary>
        internal static string LicenseInvalidFileTypes {
            get {
                return ResourceManager.GetString("LicenseInvalidFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both license and key files are required..
        /// </summary>
        internal static string LicenseKeyRequired {
            get {
                return ResourceManager.GetString("LicenseKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License and Key uploaded successfully..
        /// </summary>
        internal static string LicenseKeyUploaded {
            get {
                return ResourceManager.GetString("LicenseKeyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maintenance device already exists..
        /// </summary>
        internal static string MaintenanceDeviceExits {
            get {
                return ResourceManager.GetString("MaintenanceDeviceExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This maintenance plan is already exists..
        /// </summary>
        internal static string MaintenancePlanExists {
            get {
                return ResourceManager.GetString("MaintenancePlanExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New token generated successfully..
        /// </summary>
        internal static string NewTokenGenerated {
            get {
                return ResourceManager.GetString("NewTokenGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available to generate insights..
        /// </summary>
        internal static string NoDataAvailableForInsights {
            get {
                return ResourceManager.GetString("NoDataAvailableForInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid data available to generate insights..
        /// </summary>
        internal static string NoValidDataAvailableForInsights {
            get {
                return ResourceManager.GetString("NoValidDataAvailableForInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid device rows found in the Excel file..
        /// </summary>
        internal static string NoValidDeviceRows {
            get {
                return ResourceManager.GetString("NoValidDeviceRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid data insights available based on the selection..
        /// </summary>
        internal static string NoValidInsightsBasedOnSelection {
            get {
                return ResourceManager.GetString("NoValidInsightsBasedOnSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy Rate Comparison.
        /// </summary>
        internal static string OccupancyRateComparison {
            get {
                return ResourceManager.GetString("OccupancyRateComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password you entered does not match our records..
        /// </summary>
        internal static string OldPasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("OldPasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP has expired or is invalid. Please request a new one to continue..
        /// </summary>
        internal static string OtpExpiredOrInvalid {
            get {
                return ResourceManager.GetString("OtpExpiredOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An OTP has been sent to your registered email address..
        /// </summary>
        internal static string OtpSuccessfullySentToEmail {
            get {
                return ResourceManager.GetString("OtpSuccessfullySentToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP has been successfully validated..
        /// </summary>
        internal static string OtpSuccessfullyValidated {
            get {
                return ResourceManager.GetString("OtpSuccessfullyValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. Owner {0} is no longer authorized. Validity expired on {1}..
        /// </summary>
        internal static string OwnerValidityExpired {
            get {
                return ResourceManager.GetString("OwnerValidityExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Validity Expired.
        /// </summary>
        internal static string OwnerValidityExpiredTitle {
            get {
                return ResourceManager.GetString("OwnerValidityExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent site not found.
        /// </summary>
        internal static string ParentSiteNotFound {
            get {
                return ResourceManager.GetString("ParentSiteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has already been reset.Please log in with your current password..
        /// </summary>
        internal static string PasswordAlreadyReset {
            get {
                return ResourceManager.GetString("PasswordAlreadyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully..
        /// </summary>
        internal static string PasswordSuccessfullyReset {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF file generated successfully..
        /// </summary>
        internal static string PdfGenerated {
            get {
                return ResourceManager.GetString("PdfGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People &amp; Vehicle Count.
        /// </summary>
        internal static string PeopleAndVehicleCount {
            get {
                return ResourceManager.GetString("PeopleAndVehicleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People Count.
        /// </summary>
        internal static string PeopleCount {
            get {
                return ResourceManager.GetString("PeopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People Count.
        /// </summary>
        internal static string PeopleCountLabel {
            get {
                return ResourceManager.GetString("PeopleCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People Occupancy.
        /// </summary>
        internal static string PeopleOccupancy {
            get {
                return ResourceManager.GetString("PeopleOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People occupancy levels suggest.
        /// </summary>
        internal static string PeopleOccupancyLevelsSuggest {
            get {
                return ResourceManager.GetString("PeopleOccupancyLevelsSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Comparison Table.
        /// </summary>
        internal static string PerformanceComparisonTable {
            get {
                return ResourceManager.GetString("PerformanceComparisonTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} is not allowed to exit at this time. Allowed time: {3} - {4}.
        /// </summary>
        internal static string PermanentTimeRestrictionDesc {
            get {
                return ResourceManager.GetString("PermanentTimeRestrictionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Restriction.
        /// </summary>
        internal static string PermanentTimeRestrictionTitle {
            get {
                return ResourceManager.GetString("PermanentTimeRestrictionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission service is currently unavailable. Please try again later..
        /// </summary>
        internal static string PermissionServiceNotAvailable {
            get {
                return ResourceManager.GetString("PermissionServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX certificate must contain a private key.
        /// </summary>
        internal static string PFXCertificateContainPrivatekey {
            get {
                return ResourceManager.GetString("PFXCertificateContainPrivatekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error occurred while processing PFX certificate.
        /// </summary>
        internal static string PFXCertificateError {
            get {
                return ResourceManager.GetString("PFXCertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must have .pfx extension.
        /// </summary>
        internal static string PFXFileExtension {
            get {
                return ResourceManager.GetString("PFXFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX file is required.
        /// </summary>
        internal static string PFXFileRequired {
            get {
                return ResourceManager.GetString("PFXFileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX file size cannot exceed 10MB.
        /// </summary>
        internal static string PFXFileSize {
            get {
                return ResourceManager.GetString("PFXFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been successfully added..
        /// </summary>
        internal static string RecordAdded {
            get {
                return ResourceManager.GetString("RecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been successfully deleted..
        /// </summary>
        internal static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert the record..
        /// </summary>
        internal static string RecordNotInserted {
            get {
                return ResourceManager.GetString("RecordNotInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been retrieved successfully..
        /// </summary>
        internal static string RecordRetrieved {
            get {
                return ResourceManager.GetString("RecordRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been successfully updated..
        /// </summary>
        internal static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Name.
        /// </summary>
        internal static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database restored successfully..
        /// </summary>
        internal static string RestoreDatabase {
            get {
                return ResourceManager.GetString("RestoreDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore failed: Invalid file or Unauthorized user..
        /// </summary>
        internal static string RestoreFailedInvalidFile {
            get {
                return ResourceManager.GetString("RestoreFailedInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is already assigned to another user..
        /// </summary>
        internal static string RoleExists {
            get {
                return ResourceManager.GetString("RoleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name {0} already exist..
        /// </summary>
        internal static string RoleNameExits {
            get {
                return ResourceManager.GetString("RoleNameExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample file not found..
        /// </summary>
        internal static string SampleFileNotFound {
            get {
                return ResourceManager.GetString("SampleFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        internal static string Sites {
            get {
                return ResourceManager.GetString("Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is currently unavailable or offline. Please verify the site address and try again..
        /// </summary>
        internal static string SiteUnavailable {
            get {
                return ResourceManager.GetString("SiteUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Insights.
        /// </summary>
        internal static string SummaryInsights {
            get {
                return ResourceManager.GetString("SummaryInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System auto-exited: same vehicle entered again without a recorded exit..
        /// </summary>
        internal static string SystemAutoExited {
            get {
                return ResourceManager.GetString("SystemAutoExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Test define.
        /// </summary>
        internal static string TestDefine {
            get {
                return ResourceManager.GetString("TestDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Restriction.
        /// </summary>
        internal static string TimeRestriction {
            get {
                return ResourceManager.GetString("TimeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total People Count.
        /// </summary>
        internal static string TotalPeopleCount {
            get {
                return ResourceManager.GetString("TotalPeopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Vehicle Count.
        /// </summary>
        internal static string TotalVehicleCount {
            get {
                return ResourceManager.GetString("TotalVehicleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Composition (People Vs Vehicles).
        /// </summary>
        internal static string TrafficCompositionPeopleVsVehicles {
            get {
                return ResourceManager.GetString("TrafficCompositionPeopleVsVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unauthorized access attempt has been detected..
        /// </summary>
        internal static string UnauthorizedAccessAttempt {
            get {
                return ResourceManager.GetString("UnauthorizedAccessAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource..
        /// </summary>
        internal static string UnauthorizedAccessResource {
            get {
                return ResourceManager.GetString("UnauthorizedAccessResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Vehicle.
        /// </summary>
        internal static string UnauthorizedVehicle {
            get {
                return ResourceManager.GetString("UnauthorizedVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload session not found.
        /// </summary>
        internal static string UploadSessionForDB {
            get {
                return ResourceManager.GetString("UploadSessionForDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To receive notifications from iDRAC, the Vision Insight application URL must use HTTPS and contain a valid IP address or domain name..
        /// </summary>
        internal static string UrlDomainValidation {
            get {
                return ResourceManager.GetString("UrlDomainValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user limit has been reached. Please contact your administrator to upgrade the license..
        /// </summary>
        internal static string UserLimitExceededLicense {
            get {
                return ResourceManager.GetString("UserLimitExceededLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in successfully..
        /// </summary>
        internal static string UserLoggedIn {
            get {
                return ResourceManager.GetString("UserLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} cannot enter. Maximum allowed vehicles ({3}) already in..
        /// </summary>
        internal static string VehicleCounLimit {
            get {
                return ResourceManager.GetString("VehicleCounLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Count.
        /// </summary>
        internal static string VehicleCount {
            get {
                return ResourceManager.GetString("VehicleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle entered successfully.
        /// </summary>
        internal static string VehicleEnteredSuccessfully {
            get {
                return ResourceManager.GetString("VehicleEnteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle exited successfully.
        /// </summary>
        internal static string VehicleExitedSuccssfully {
            get {
                return ResourceManager.GetString("VehicleExitedSuccssfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Limit Reached.
        /// </summary>
        internal static string VehicleLimitReached {
            get {
                return ResourceManager.GetString("VehicleLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} is not allowed at this time. Allowed time: {3} - {4}.
        /// </summary>
        internal static string VehicleNotAllowedTime {
            get {
                return ResourceManager.GetString("VehicleNotAllowedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Occupancy.
        /// </summary>
        internal static string VehicleOccupancy {
            get {
                return ResourceManager.GetString("VehicleOccupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle occupancy levels suggest.
        /// </summary>
        internal static string VehicleOccupancyLevelsSuggest {
            get {
                return ResourceManager.GetString("VehicleOccupancyLevelsSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Owner not found for {0} {1} {2}.
        /// </summary>
        internal static string VehicleOwnerNotFound {
            get {
                return ResourceManager.GetString("VehicleOwnerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Owner not found.
        /// </summary>
        internal static string VehicleOwnerNotFoundNotification {
            get {
                return ResourceManager.GetString("VehicleOwnerNotFoundNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to change this user’s details..
        /// </summary>
        internal static string ViAdminUserPermisssion {
            get {
                return ResourceManager.GetString("ViAdminUserPermisssion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Time Restriction.
        /// </summary>
        internal static string VisitorTimeRestriction {
            get {
                return ResourceManager.GetString("VisitorTimeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} is not allowed to exit. Visitor valid period: {3} - {4}.
        /// </summary>
        internal static string VisitorTimeRestrictionDesc {
            get {
                return ResourceManager.GetString("VisitorTimeRestrictionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Time Restriction.
        /// </summary>
        internal static string VisitorTimeRestrictionTitle {
            get {
                return ResourceManager.GetString("VisitorTimeRestrictionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} is not allowed to enter. Visitor valid period: {3} - {4}.
        /// </summary>
        internal static string VisitorValidPeriod {
            get {
                return ResourceManager.GetString("VisitorValidPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        internal static string Zones {
            get {
                return ResourceManager.GetString("Zones", resourceCulture);
            }
        }
    }
}
